server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/EachannWang/SpringcloudConfig/
          searchPaths: respo
          username:
          password:
